version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - "5432"

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.8
    environment:
      DBT_PROFILE_DIR: /dbt
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    working_dir: /dbt
    volumes:
      - ./dbt:/dbt
    depends_on:
      - db
    command: dbt run

volumes:
  db-data:
